### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by edwardpayton** [jessedobbelaere/mysql-ssh-backups#1]
Hey, first of all great work, your script has got me over a hurdle I was stuck on.

One issue I encountered was regarding the Paramiko connect class. Your script has `look_for_keys=False` which prevented a connection being made (for me anyway). 

Forgive me if I'm missing something (I'm a Python newbie!), but removing that argument made the script work perfectly.

**Comment by jessedobbelaere** [comment]
Great suggestion! Seems to be still working fine for me without it.
I fixed this in e30a7c4d9741397fbd1a1385be178251ad79c7e2 :)
